name: Bonjour

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message
        run: echo "Bonjour depuis GitHub Actions !"
